version: '2'
services:

 mysql:
  image: mysql
  container_name: mYsQlDb
  volumes:
   - mysql:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=datadb
   - MYSQL_USER=qwerty
   - MYSQL_PASSWORD=qwerty
  ports:
   - "3306:3306"
volumes:
 mysql: